spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.83.133:3306/touch_air_mall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.83.133:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  application:
    name: touch-air-mall-ware
  zipkin:
    base-url: http://192.168.83.133:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: 192.168.83.133
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 11000

seata:
  #是否开启spring-boot 自动装配
  enabled: true
  #自定义事务组名称
  tx-service-group: order-mall-group
  #是否开启数据源自动代理
  enable-auto-data-source-proxy: true
  service:
    vgroupMapping:
      order-mall-group: default
    grouplist:
      #服务器上seata的地址
      default: localhost:8091
    enable-degrade: false
  application-id: ${spring.application.name}


management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true