spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.83.133:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  application:
    name: touch-air-mall-cart
  zipkin:
    base-url: http://192.168.83.133:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  redis:
    host: 192.168.83.133
    port: 6379
    session:
      store-type: redis

server:
  port: 13000
  servlet:
    session:
      timeout: 30m

#actuator统计审计信息
management:
  endpoints:
    web:
      exposure:
        include: "*"

mall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
feign:
  sentinel:
    enabled: true