spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.83.133:3306/touch_air_mall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.83.133:8848
  application:
    name: touch-air-mall-product
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    #关闭 thymeleaf 缓存
    cache: false
  redis:
    host: 192.168.83.133
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      #key前缀 区别redis中其他非缓存数据
#      key-prefix: CACHE_
      #key前缀是否使用
      use-key-prefix: true
      #是否缓存空值，防止缓存穿透
      cache-null-values: true
#    cache-names:


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 12000
