spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.83.133:3306/touch_air_mall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.83.133:8848
    alicloud:
      access-key: LTAI4GDNygty37irjb6t8Nrm
      secret-key: gfgG6dtUTuvktTqKc4BlQihpNuZbOa
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
  application:
    name: touch-air-mall-product

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 12000

