spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.83.133:8848
  application:
    name: touch-air-mall-search
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    port: 6379
    host: 192.168.83.133
server:
  port: 14000
  servlet:
    session:
      timeout: 30m

