spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.83.133:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  application:
    name: touch-air-mall-auth-server
  zipkin:
    base-url: http://192.168.83.133:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  redis:
    host: 192.168.83.133
    port: 6379
  session:
    store-type: redis
server:
  port: 20000
  servlet:
    session:
      timeout: 30m

#actuator统计审计信息
management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true