spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.83.133:8848
  application:
    name: touch-air-mall-auth-server
  thymeleaf:
    cache: false
  redis:
    host: 192.168.83.133
    port: 6379
  session:
    store-type: redis
server:
  port: 20000
  servlet:
    session:
      timeout: 30m